#!/usr/bin/env python

import os, sys, glob, eyeD3

def main():
  ss = songs('.')
  js = map(song_js, ss)
  db = '[%s]' % (','.join(js))
  write(db)  

def songs(dir):
  res = []
  # unsafe for symlink cycles
  for root, dirs, fnms in os.walk(dir, followlinks=True):
    ss = [os.path.join(root, fnm) for fnm in fnms]
    ss = filter(ismp3, ss)
    res.extend(ss)
  return res

def ismp3(s):
  return s.lower().endswith('mp3')

def song_js(path):
    tag = eyeD3.Tag()
    tag.link(path)
    return '''
{ path   : "%s"
, genre  : "%s"
, artist : "%s"
, album  : "%s"
, year   : "%s"
, track  : "%s"
, total  : "%s"
, title  : "%s"
}
''' % ( tag.linkedFile.name
      , tag.getGenre().getName().lower()
      , tag.getArtist()
      , tag.getAlbum()
      , tag.getYear()
      , tag.getTrackNum()[0]
      , tag.getTrackNum()[1]
      , tag.getTitle()
      )

def write(db):
  try:
    f = open('songdb', 'w')
    f.write(db)
    f.close()
  except:
    sys.error('Error: unable to write songdb')

main()
