#!/usr/bin/env bash

# TODO check that eyeD3 is available

# do not split on spaces in file names
IFS=$(echo -en "\n\b")

function main {
    print_dir .
}

function print_dir {
  dir="$1"
  echo "["
  first=true
  for song in $(find -L $dir -name '*.mp3'); do
    if $first; then
      first=false
    else
      echo ","
    fi
    print_info "$song"
  done
  echo "];"
}

function print_info {
  song="$1"
  info=$(eyeD3 --no-color "$song")

  tit=$(extract_field "$info" 'title:'  'artist:')
  art=$(extract_field "$info" 'artist:' 'album:')
  alb=$(extract_field "$info" 'album:'  'year:')
  yer=$(extract_field "$info" 'year:'   'track:')
  trk=$(extract_field "$info" 'track:'  'genre:')
  gen=$(extract_field_non_greedy "$info" 'genre:'  '(')

  tot=$(echo $trk | cut -d '/' -f 2)
  trk=$(echo $trk | cut -d '/' -f 1)

  gen=$(echo $gen | tr [:upper:] [:lower:])

  echo "
{ path   : \"$(echo $song | sed 's:^\./::')\"
, genre  : \"$gen\"
, artist : \"$art\"
, album  : \"$alb\"
, year   : \"$yer\"
, track  : \"$trk\"
, total  : \"$tot\"
, title  : \"$tit\"
}
"
}

# extract field from $1 between delimiters $2 and $3
function extract_field {
  echo $1 | sed -e "s/.*$2\(.*\)$3.*/\1/" \
                -e 's/^[ \t]*//' \
                -e 's/[ \t]*$//'
}

function extract_field_non_greedy {
  echo $1 | sed -e "s/.*$2\([^$3]*\)$3.*/\1/" \
                -e 's/^[ \t]*//' \
                -e 's/[ \t]*$//'
}


main > .songdb

