#!/usr/bin/env python

from __future__ import print_function
import os
import glob
import eyeD3

def song_to_js(path):
    tag = eyeD3.Tag()
    tag.link(path)
    art_imgs = glob.glob('%s/*.jpg' %
                         os.path.dirname(path))
    art_img = ""
    if len(art_imgs) > 0:
        art_img = art_imgs[0]
    return """
{ path   : "%s"
, genre  : "%s"
, artist : "%s"
, album  : "%s"
, year   : "%s"
, track  : "%s"
, total  : "%s"
, title  : "%s"
, art    : "%s"
},
""" % ( tag.linkedFile.name
      , tag.getGenre().getName()
      , tag.getArtist()
      , tag.getAlbum()
      , tag.getYear()
      , tag.getTrackNum()[0]
      , tag.getTrackNum()[1]
      , tag.getTitle()
      , art_img)

def print_dir(stream, dir):
    print('[', file=stream)
    # not safe in the face of symlink cycles
    for root, dirs, filenames in os.walk(dir, followlinks=True):
        files = [os.path.join(root, fn) for fn in filenames]
        [print(song_to_js(song), file=stream) for song in
            [song for song in files if song.lower().endswith('mp3')]]
    print(']', file=stream)

def main():
    print_dir(open('.songdb', 'w'), '.')

if __name__ == '__main__':
    main()
