#!/bin/bash

if [ ! -x "$(which webfsd)" ]; then
  echo "webfsd must be installed to use this simple server" \
       "(Debian/Ubuntu package 'webfs')."
  exit -1
fi

# -b username:password to add basic auth to the content

# need root both to bind to 80 and to setuid
webfsd -p 80 -u nobody -f index.html $*
